/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagl;

import javagl.core.managers.EngineManager;
import javagl.core.managers.WindowManager;
import javagl.core.utils.Constants;

public class App {
    // The window object of the app.
    private static WindowManager window;

    // The engine object of the app.
    private static EngineManager engine;

    // The current game object to run in the window.
    private static TestGame game;

    public static void main(String[] args) {
        window = new WindowManager(Constants.TITLE, 1600, 900, false);
        game = new TestGame();
        engine = new EngineManager();

        try {
            engine.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static WindowManager getWindow() {
        return window;
    }

    public static TestGame getGame() {
        return game;
    }
}
