/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagl;

import org.lwjgl.Version;

public class App {
    public static void main(String[] args) {
        System.out.println(Version.getVersion());
    }
}
